# Generated by Django 6.0.5 on 2026-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('vision_data', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=list)),
                ('openai_result', models.JSONField(default=dict)),
                ('deepseek_result', models.JSONField(default=dict)),
            ],
        ),
    ]
