# Generated by Django 6.0.5 on 2026-06-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productrequest_modelresult_finalresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
