# Generated by Django 6.0.5 on 2026-07-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='duty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='vat',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
